### ISSUE TITLE
Web build is always showing 2 images of the card at the same time

### ISSUE THREAD

**Issue by mvershinin-chwy** [SimformSolutionsPvtLtd/flutter_credit_card#14]
**Describe the bug**
When run Web build. The widget is always showing 2 images of the card at the same time

![image](https://user-images.githubusercontent.com/38470676/75307977-2b2dbb00-581b-11ea-850c-041816c21538.png)

**Comment by Bilonik** [comment]
Same issue

**Comment by fvisticot** [comment]
Same issue
<img width="367" alt="Capture d’écran 2020-05-26 à 21 19 27" src="https://user-images.githubusercontent.com/153679/82941435-a1ff5f00-9f96-11ea-8e70-84b374715328.png">

**Comment by YahiaRagae** [comment]
Same Issue 
![Screen Shot 2020-06-10 at 1 17 46 PM](https://user-images.githubusercontent.com/7969139/84216154-c7ef3c80-ab1c-11ea-9c3f-207e45db0f53.png)

**Comment by DanielToubul** [comment]
have the same issue, somebody got it working since then?

**Comment by DhavalRKansara** [comment]
@mvershinin-chwy  @fvisticot @YahiaRagae @realitymolder Hi Guys I have tested the same with the latest release [flutter_credit_card: ^3.0.2](https://pub.dev/packages/flutter_credit_card) and I am bot able replicate the same. Can you please test it once with the latest release and Let us know if it's still reproducible or not?

**Comment by DhavalRKansara** [comment]
I’m closing this issue because it has been inactive for months. This probably means that it is not reproducible or has been fixed in a newer version. Please reopen if you still encounter this issue with the [flutter_credit_card: ^3.0.3](https://pub.dev/packages/flutter_credit_card). Also, You can also contribute directly by providing a patch or solution. Thank you!
