### ISSUE TITLE
Initialize values

### ISSUE THREAD

**Issue by MarceloRab** [SimformSolutionsPvtLtd/flutter_credit_card#6]
Could you add values at startup to help with editing?

```dart
void initState() {
super.initState();

createCreditCardModel();

onCreditCardModelChange = widget.onCreditCardModelChange;

cvvFocusNode.addListener(textFieldFocusDidChange);

_cardNumberController.text = cardNumber;
_expiryDateController.text = expiryDate;
_cardHolderNameController.text = cardHolderName;
```

**Comment by BirjuVachhani** [comment]
@MarceloRab Could you please provide more info on why this is needed?

**Comment by VinceERS** [comment]
Hello, I would like to add a little input for this question as I have a similar request.

My use case is for taking payments on orders, and to speed up the credit card entry I would like to initialize the form with the customer's name from the order.

Secondly (and maybe the same feature), I was wondering if there is a way to clear all the text in the form so that changing entry for a different card could be very quick, e.g. I add a clear/reset button to my app's ui.

Thanks very much for this package, I found it really useful and it looks good!

**Comment by sam-parks** [comment]
This would help the editing of credit card information during checkout. Here is a video of where I would expect initial values to be: 



[credit_card.gif.zip](https://github.com/simformsolutions/flutter_credit_card/files/4908695/credit_card.gif.zip)

**Comment by smelcher** [comment]
I am also looking to be able to default in the card, name, cvv, and date.  In my scenario, the card is stored on the phone and I want to default the information in so that they don't have to type it all in every time

**Comment by AsadAMalikDeveloper** [comment]
> I am also looking to be able to default in the card, name, cvv, and date. In my scenario, the card is stored on the phone and I want to default the information in so that they don't have to type it all in every time

Did you find any solution?
