### ISSUE TITLE
CVV comes before Holder Name in CreditCardForm

### ISSUE THREAD

**Issue by shadysamir** [SimformSolutionsPvtLtd/flutter_credit_card#8]
The CVV form input comes before the card holder name while it has:
```dart
textInputAction: TextInputAction.done
```
The animated gif in README shows CVV field coming last.

**Comment by jairoareyes** [comment]
I have the same question, did you use this widget?

**Comment by DhavalRKansara** [comment]
Hello, @shadysamir & @jairoareyes I didn't get your query completely, Can you guys please share some block of code or screenshot which describe your issue in detail? Also, it's too old and we have released a new version of this package last month so It will be great if you guys test the same with [flutter_credit_card: ^3.0.2](https://pub.dev/packages/flutter_credit_card) and let us know if it is still reproducible.

**Comment by DhavalRKansara** [comment]
I’m closing this issue because it has been inactive for months. This probably means that it is not reproducible or has been fixed in a newer version. Please reopen if you still encounter this issue with the [flutter_credit_card: ^3.0.3](https://pub.dev/packages/flutter_credit_card). Also, You can also contribute directly by providing a patch or solution. Thank you!
