### ISSUE TITLE
Handle changes of values in didChangeDependencies of CreditCardForm

### ISSUE THREAD

**Issue by bismarabia** [SimformSolutionsPvtLtd/flutter_credit_card#87]
Initializing values is done in this method **createCreditCardModel()**, and it's being called only in **initState()**.

I believe this method should also be called in **didChangeDependencies()** method as well to reflect the new changes of
cardNumber
expiryDate
cardHolderName
cvvCode

**Comment by DhavalRKansara** [comment]
Hi @bismarabia, Can you please share more information that in which scenarios it will be helpful to you to initialise `createCreditCardModel` inside `didChangeDependencies`? 

For now, we are initialising it once in the `initState` and after that, we are simply updating it with whatever input is provided by the end user in the respective text fields.

**Comment by DhavalRKansara** [comment]
I’m closing this issue because it has been inactive for months. This probably means that it is not reproducible or has been fixed in a newer version. Please reopen if you still encounter this issue with the [flutter_credit_card: ^3.0.3](https://pub.dev/packages/flutter_credit_card). Also, You can also contribute directly by providing a patch or solution. Thank you!
